# Generated by Django 2.1.11 on 2021-01-23 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=128)),
                ('state_province', models.CharField(blank=True, max_length=128)),
                ('hospital_organization', models.CharField(blank=True, max_length=128)),
                ('region2', models.CharField(blank=True, max_length=128)),
                ('city2', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('specialty', models.CharField(blank=True, max_length=128)),
                ('specialty2', models.CharField(blank=True, max_length=128)),
                ('learn_event', models.CharField(blank=True, max_length=128)),
                ('country2', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(default=datetime.datetime.now)),
                ('leave_time', models.DateTimeField(default=datetime.datetime.now)),
                ('time_in_session', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.TimeField(default=datetime.datetime.now)),
                ('approval_status', models.CharField(blank=True, max_length=128)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='core.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='core.Webinar'),
        ),
        migrations.AddField(
            model_name='session',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.Ticket'),
        ),
    ]
