# Generated by Django 2.1.11 on 2021-01-24 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='minutes_for_certificate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='join_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='leave_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_session', to='core.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.Participant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.Webinar'),
        ),
    ]
