# Generated by Django 2.1.11 on 2021-01-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210124_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cert_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
